/** 內功類型 */
export enum InnerSkillType {
  /** 七秀冰心訣 */
  QI_XIU_BING_XIN_JUE = 'QI_XIU_BING_XIN_JUE',
  /** 七秀雲裳心經 */
  QI_XIU_YUN_SHANG_XIN_JING = 'QI_XIU_YUN_SHANG_XIN_JING',
  /** 萬花花間游 */
  WAN_HUA_HUA_JIAN_YOU = 'WAN_HUA_HUA_JIAN_YOU',
  /** 萬花離經易道 */
  WAN_HUA_LI_JING_YI_DAO = 'WAN_HUA_LI_JING_YI_DAO',
  /** 五毒毒經 */
  WU_DU_DU_JING = 'WU_DU_DU_JING',
  /** 五毒補天訣 */
  WU_DU_BU_TIAN_JUE = 'WU_DU_BU_TIAN_JUE',
  /** 長歌莫問 */
  CHANG_GE_MO_WEN = 'CHANG_GE_MO_WEN',
  /** 長歌相知 */
  CHANG_GE_XIANG_ZHI = 'CHANG_GE_XIANG_ZHI',
  /** 藥宗無方 */
  YAO_ZONG_WU_FANG = 'YAO_ZONG_WU_FANG',
  /** 藥宗靈素 */
  YAO_ZONG_LING_SU = 'YAO_ZONG_LING_SU',
  /** 天策傲血戰意 */
  TIAN_CE_AO_XUE_ZHAN_YI = 'TIAN_CE_AO_XUE_ZHAN_YI',
  /** 天策鐵牢律 */
  TIAN_CE_TIE_LAO_LV = 'TIAN_CE_TIE_LAO_LV',
  /** 少林易筋經 */
  SHAO_LIN_YI_JIN_JING = 'SHAO_LIN_YI_JIN_JING',
  /** 少林洗髓經 */
  SHAO_LIN_XI_SUI_JING = 'SHAO_LIN_XI_SUI_JING',
  /** 明教焚影聖訣 */
  MING_JIAO_FEN_YING_SHENG_JUE = 'MING_JIAO_FEN_YING_SHENG_JUE',
  /** 明教明尊琉璃體 */
  MING_JIAO_MING_ZUN_LIU_LI_TI = 'MING_JIAO_MING_ZUN_LIU_LI_TI',
  /** 蒼雲分山劲 */
  CANG_YUN_FEN_SHAN_JIN = 'CANG_YUN_FEN_SHAN_JIN',
  /** 蒼雲鐵骨衣 */
  CANG_YUN_TIE_GU_YI = 'CANG_YUN_TIE_GU_YI',
  /** 純陽紫霞功 */
  CHUN_YANG_ZI_XIA_GONG = 'CHUN_YANG_ZI_XIA_GONG',
  /** 純陽太虛劍意 */
  CHUN_YANG_TAI_XU_JIAN_YI = 'CHUN_YANG_TAI_XU_JIAN_YI',
  /** 唐門天羅詭道 */
  TANG_MEN_TIAN_LUO_GUI_DAO = 'TANG_MEN_TIAN_LUO_GUI_DAO',
  /** 唐門驚羽訣 */
  TANG_MEN_JING_YU_JUE = 'TANG_MEN_JING_YU_JUE',
  /** 藏劍問水訣 */
  CANG_JIAN_WEN_SHUI_JUE = 'CANG_JIAN_WEN_SHUI_JUE',
  /** 丐幫嘯塵訣 */
  GAI_BANG_XIAO_CHEN_JUE = 'GAI_BANG_XIAO_CHEN_JUE',
  /** 霸刀北傲訣 */
  BA_DAO_BEI_AO_JUE = 'BA_DAO_BEI_AO_JUE',
  /** 蓬萊靈海訣 */
  PENG_LAI_LING_HAI_JUE = 'PENG_LAI_LING_HAI_JUE',
  /** 凌雪隱龍訣 */
  LING_XUE_YIN_LONG_JUE = 'LING_XUE_YIN_LONG_JUE',
  /** 衍天太玄經 */
  YAN_TIAN_TAI_XUAN_JING = 'YAN_TIAN_TAI_XUAN_JING',
  /** 刀宗孤鋒訣 */
  DAO_ZONG_GU_FENG_JUE = 'DAO_ZONG_GU_FENG_JUE',
  /** 萬靈山海心訣 */
  WAN_LING_SHAN_HAI_XIN_JUE = 'WAN_LING_SHAN_HAI_XIN_JUE',
}
