/** 門派類型 */
export enum SectType {
  /** 大俠門派 */
  DA_XIA = 'DA_XIA',
  /** 純陽門派 */
  CHUN_YANG = 'CHUN_YANG',
  /** 七秀門派 */
  QI_XIU = 'QI_XIU',
  /** 萬花門派 */
  WAN_HUA = 'WAN_HUA',
  /** 少林門派 */
  SHAO_LIN = 'SHAO_LIN',
  /** 天策門派 */
  TIAN_CE = 'TIAN_CE',
  /** 藏劍門派 */
  CANG_JIAN = 'CANG_JIAN',
  /** 五毒門派 */
  WU_DU = 'WU_DU',
  /** 唐門門派 */
  TANG_MEN = 'TANG_MEN',
  /** 明教門派 */
  MING_JIAO = 'MING_JIAO',
  /** 丐幫門派 */
  GAI_BANG = 'GAI_BANG',
  /** 蒼雲門派 */
  CANG_YUN = 'CANG_YUN',
  /** 長歌門派 */
  CHANG_GE = 'CHANG_GE',
  /** 霸刀門派 */
  BA_DAO = 'BA_DAO',
  /** 蓬萊門派 */
  PENG_LAI = 'PENG_LAI',
  /** 凌雪門派 */
  LING_XUE = 'LING_XUE',
  /** 衍天門派 */
  YAN_TIAN = 'YAN_TIAN',
  /** 藥宗門派 */
  YAO_ZONG = 'YAO_ZONG',
  /** 刀宗門派 */
  DAO_ZONG = 'DAO_ZONG',
  /** 萬靈門派 */
  WAN_LING = 'WAN_LING',
}
